### ISSUE TITLE
feat: API Key Visibility Toggle with Placeholder Text

### ISSUE THREAD

**Issue by samantha-t28** [luniai/github-code-review#13]
As a [user],

I want to toggle the visibility of my API key input.

So that I can verify the key I entered without compromising its security.

Acceptance Criteria:

1. The API key input field includes a visibility toggle icon (e.g., an eye icon.
2. The default state of the API key is hidden (masked with dots) with a hidden eye icon at the end of the input field.
3.  Clicking the visibility toggle icon reveals the API key with the visible eye icon.
4. Each API key input field includes a placeholder text indicating the type of key (e.g., "open-api-key" for OpenAI and "grog-api-key" for Grog).

Tasks/Sub-tasks:

Development:

1. Add visibility toggle icon (eye icon) next to the API key input field.
2. Implement functionality to toggle between hidden and visible states for the API key.
3. Add Placeholder Text:
- Add placeholder text ("open-api-key" for the OpenAI API Key input field and "groq-api-key" for the Groq API Key input field) to guide the user.

**Requirements**:
1. Add SVG for hidden eye icon
```
<svg width="32" height="32" viewBox="0 0 32 32" fill="none" xmlns="http://www.w3.org/2000/svg">
<g clip-path="url(#clip0_9_3408)">
<path d="M19.96 19.96C18.8204 20.8287 17.4328 21.3099 16 21.3333C11.3334 21.3333 8.66669 16 8.66669 16C9.49595 14.4546 10.6461 13.1044 12.04 12.04M14.6 10.8267C15.0589 10.7192 15.5287 10.6655 16 10.6667C20.6667 10.6667 23.3334 16 23.3334 16C22.9287 16.7571 22.4461 17.4698 21.8934 18.1267M17.4134 17.4133C17.2303 17.6098 17.0095 17.7674 16.7641 17.8767C16.5188 17.9861 16.254 18.0448 15.9854 18.0496C15.7169 18.0543 15.4501 18.0049 15.2011 17.9043C14.9521 17.8037 14.7258 17.654 14.5359 17.4641C14.346 17.2742 14.1963 17.048 14.0957 16.7989C13.9951 16.5499 13.9457 16.2831 13.9504 16.0146C13.9552 15.7461 14.014 15.4812 14.1233 15.2359C14.2326 14.9906 14.3902 14.7698 14.5867 14.5867M8.66669 8.66666L23.3334 23.3333" stroke="#1E1E1E" stroke-width="1.6" stroke-linecap="round" stroke-linejoin="round"/>
</g>
<defs>
<clipPath id="clip0_9_3408">
<rect width="16" height="16" fill="white" transform="translate(8 8)"/>
</clipPath>
</defs>
</svg>
```
2. Add SVG for unhidden eye icon
```
<svg width="32" height="32" viewBox="0 0 32 32" fill="none" xmlns="http://www.w3.org/2000/svg">
<g clip-path="url(#clip0_9_3407)">
<path d="M8.66669 16C8.66669 16 11.3334 10.6667 16 10.6667C20.6667 10.6667 23.3334 16 23.3334 16C23.3334 16 20.6667 21.3333 16 21.3333C11.3334 21.3333 8.66669 16 8.66669 16Z" stroke="#1E1E1E" stroke-width="1.6" stroke-linecap="round" stroke-linejoin="round"/>
<path d="M16 18C17.1046 18 18 17.1046 18 16C18 14.8954 17.1046 14 16 14C14.8955 14 14 14.8954 14 16C14 17.1046 14.8955 18 16 18Z" stroke="#1E1E1E" stroke-width="1.6" stroke-linecap="round" stroke-linejoin="round"/>
</g>
<defs>
<clipPath id="clip0_9_3407">
<rect width="16" height="16" fill="white" transform="translate(8 8)"/>
</clipPath>
</defs>
</svg>
```

**Screenshot**:
![Image](https://github.com/user-attachments/assets/41a308d8-443b-4160-b0f2-21837db97b38)
![Image](https://github.com/user-attachments/assets/cefae56f-68ef-486d-9f75-71c2c2dbce67)

**Comment by spudoodle** [comment]
Hey, I would like to work on this

**Comment by opauloh** [comment]
Hi @slusy, apologies for the delay in the reply, do you still want to work on this task?

**Comment by opauloh** [comment]
Update, adding design specs (CSS) for this component

![image](https://github.com/user-attachments/assets/7492c1c6-39e1-410d-988d-746edc67aed6)

![image](https://github.com/user-attachments/assets/69c86550-5466-446d-b867-4cce0adeffc9)

**Comment by spudoodle** [comment]
@opauloh I can work on it

**Comment by opauloh** [comment]
Thanks @slusy, I've assigned you to this issue
