### ISSUE TITLE
List some gpt models that can be used

### ISSUE THREAD

**Issue by opauloh** [luniai/github-code-review#5]
Currently, the model is a free text input, which is nice but the user needs to go to the [Chat GPT models](https://platform.openai.com/docs/models) page to know what other models it can use:

![image](https://github.com/user-attachments/assets/6fe70970-7136-4bb7-86f4-5b993e524a1a)

My suggestion is that we either use a [Datalist](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/datalist) element to keep the open text and provide some suggestions or/and add some examples on the bottom of the field of which other models could be used and a link.

Example of what instruction can be added on the bottom:

Which ChatPGT model to use, some options are `gpt-4o`, `gpt-4o-mini`, `gpt-4-turbo`, `gpt-4`, and `gpt-3.5-turbo`). Check the [Chat GPT models page](https://platform.openai.com/docs/models) for all currently available models.

**Comment by samantha-t28** [comment]
Hi! I would like to work on this issue. Could you please assign it to me?

**Comment by opauloh** [comment]
> Hi! I would like to work on this issue. Could you please assign it to me?

Hi, thanks for your interest in contributing to this project, I've assigned it to you
